server:
  port: 8082
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
hm:
  db:
    database: hm-cart
    port: 3306
  swagger:
    title: "黑马商城购物车接口文档"
    package: com.hmall.cart.controller

spring:
  cloud:
    sentinel:
      http-method-specify: true
      transport:
        dashboard: localhost:8090